// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://cvphndlpnjnkgnnasrva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cGhuZGxwbmpua2dubmFzcnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTE4MzQsImV4cCI6MjA2ODAyNzgzNH0.Ur0wHJWH27vEorHAA7YLISTggdfIn4eqlpsphNguEaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});